### ISSUE TITLE
Calendar not displaying

### ISSUE THREAD

**Issue by Jerrybear16** [fantasycalendar/Fantasy-Calendar#163]
I made a calendar a while back and I tried to access it again. When I open the calendar a few errors pop up and the calendar does not display.

**Comment by V13Axel** [comment]
@Jerrybear16 what errors are you getting? Feel free to drop a link to your calendar here and we'll take a look.

**Comment by Jerrybear16** [comment]
https://app.fantasy-calendar.com/calendars/fdd67eb5c1c8de028a65d1fbd83c988d

link to calendar

I think it's an issue with the display portion of the website and not the calendar specifically. I tried making a new calendar with a  preset and it also did not display, giving the same error.

**Comment by V13Axel** [comment]
What errors are you getting? That seems to load just fine for me.

**Comment by Jerrybear16** [comment]
Sorry give me a minute they're pop ups that go away after a second its hard to get it all down

**Comment by Jerrybear16** [comment]
error:
SyntaxError: expected expression but got "?"
in file "https://app.fantasy-calendar.com/js/calendar/calendar_workers.js?v=[id number] <- (this changes each time)
on line 795

**Comment by Jerrybear16** [comment]
My browser is firefox if that helps also

**Comment by V13Axel** [comment]
What version of Firefox are you using? That error seems to indicate you're using a version of Firefox that's over a year old, and doesn't support modern Javascript language features used by Fantasy Calendar. 

An easy way to find out what version you're running is to visit here: https://www.whatversion.net/firefox/

The latest is version 85, and Fantasy Calendar only officially supports the latest few versions, so if you're running anything less than Firefox 72 you'll need to update in order to use Fantasy Calendar.

**Comment by Jerrybear16** [comment]
ah. Thank you for the help and sorry for the trouble! My firefox is supposed to be auto-updating...how embarrassing.
