### ISSUE TITLE
fantasy-calendar-npm-install_1 errors when directory does not belong to user with uid 1000

### ISSUE THREAD

**Issue by L0ric0** [fantasycalendar/Fantasy-Calendar#173]
when cloning the repository as root (probably any user withhout uid 1000) and running `docker-compose up` the fantasy-calendar-npm-install_1 build will error with a permission denied, as the current dir is copied, leaving its permissions intact. there is probably a `chown -R 1000:1000` missing somewere

**Comment by V13Axel** [comment]
Whoops! You're right, this is actually fair.

It's not about a `chown`, though, as the files aren't getting _copied_, they're getting _mounted_ into the container (which runs as user 1000:1000. 

Since user 1000 assumes a single-user developer machine, that should be updated to run as the current user instead. Thanks for pointing this one out.
