### ISSUE TITLE
unable to reverse proxy 

### ISSUE THREAD

**Issue by L0ric0** [fantasycalendar/Fantasy-Calendar#175]
at the moment there is no documentation how to do a set up with docker and then reverseproxy that to a subdirectory of an existing site.

The main problem is that all links on the proxed site lead to localhost:9980 and there does not seem to be an option to change that

**Comment by V13Axel** [comment]
FC's internal links are generated with Laravel's (URL Generation)[https://laravel.com/docs/8.x/urls], which relies on having an environment variable of `APP_URL` set to whatever URL the app should be served at. As with any Laravel app, as long as that environment variable is set, you should be able to host it behind whatever proxy you'd like.

The fact that you're serving up on 9980, however, compels me to make sure you're not using our default `docker-compose.yml` file. I don't recommend doing that, for a host of reasons: 

1. That file is designed for development of FC, not hosting, and includes unnecessary things like running `selenium` for Laravel Dusk tests
2. The `npm-install` and `composer-install` services that it runs load development dependencies, not production ones
3. Port 9980 is served up through `browser-sync`, a program that watches for changes on your local filesystem and reloads browsers connected to it (designed for development).
4. Our own environment variables are hard-coded into it
5. That file is subject to change any time (and actually _will be_, very soon), which could very much mean we break a custom deployment the next time you pull on your copy of the repo.

---

If you're going to host FC using Docker, you'll want to look at [docker-compose-prdtest.yml](https://github.com/fantasycalendar/Fantasy-Calendar/blob/master/docker-compose-prdtest.yml), if you're not already. 

That one sets up a deployment using the `fantasycalendar/fantasycalendar` image from Docker Hub, rather than the local copy of the code. You'll still need the code checked out though, since it imports the SQL file from `setup/database.sql` at the moment. 

As long as you update all of the environment variables to fit your own environment, you should be able to get up and running pretty quickly, even behind a reverse-proxy.

---

We actually stopped running FC's production deployment using Docker a while back, and run serverlessly in AWS Lambda at the moment, and haven't even really fully settled on that as a final solution - So having handy documentation around hosting other ways just hasn't been a priority. I'll try and find some time in the future to write up some better documentation on how to host FC in a setup that isn't like ours though.

In the mean time, if you'd like some more interactive help, feel free to drop into our Discord server. However, I'm closing this. Fantasy Calendar works fine behind reverse proxies, Docker or no Docker, you just need to know how to run Laravel apps =)
