### ISSUE TITLE
Issue with Creating Events Based on Events with Duration

### ISSUE THREAD

**Issue by SANSd20** [fantasycalendar/Fantasy-Calendar#37]
When creating an event based on and event with a duration, the new event will create an event based on each event that matches on the calendar. 

Have an event that last 10 days, show only start and end. created new event that happens on the 3rd day of that event, you get the new event 3 days after the start AND 3 days after the ending. 

If you have the 10 day event show for each day, it will show 10 of the new event, offset  by 3 days

![cal1](https://user-images.githubusercontent.com/23466008/67708761-b3de3c80-f98a-11e9-8ae5-a31fb2527b4f.png)
![cal2](https://user-images.githubusercontent.com/23466008/67708762-b3de3c80-f98a-11e9-976b-9bdc1ed3f88b.png)

**Comment by Haxxer** [comment]
This is intentional as the event with duration is happening on all of those days, so the target event happened 3 days ago, each 3 days. Try enabling "only happens once in view":
![image](https://user-images.githubusercontent.com/12858387/67717210-2a982b80-f9c5-11e9-9c2f-5276c76ac2ec.png)
This will ensure that the event only happens once.

**Comment by SANSd20** [comment]
OK, looks like that was the answer. thanks!
