### ISSUE TITLE
Events not hidden

### ISSUE THREAD

**Issue by SANSd20** [fantasycalendar/Fantasy-Calendar#53]
I'm seeing events are supposed to be hidden, when I view the calendar and am not logged in. Tested this in incognito mode in Chrome and in also tried in Edge where I have never logged into the site.

**Comment by V13Axel** [comment]
@Haxxer this seems more your wheelhouse; I haven't touched event show/hide logic, not really sure what all is involved. 

Let me know if I broke something though and I'll gladly take a look.

**Comment by Laydralae** [comment]
Can also confirm events are not hiding on Opera GX LVL1 (core: 64.0.3417.146)

**Comment by V13Axel** [comment]
So this is definitely a client-side issue, ultimately, and will require @Haxxer's attention (I have no comprehension of his event-worker logic at the moment).

However, something that is definitely helpful and at least impacts loading the **view** of a calendar, is that I've now set things up so that we don't even serve up events that are set to hide from players.

That should at least make sharing things a bit nicer for sharing with players at the moment... but it's ultimately a bandaid.
